# Generated by Django 4.2.4 on 2023-08-17 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_colour'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Colour',
            new_name='Color',
        ),
        migrations.AddField(
            model_name='person',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color', to='home.color'),
        ),
    ]
